# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g1_integration_real <- function(lower, upper, h_val, d, H) {
    .Call(`_carfima_g1_integration_real`, lower, upper, h_val, d, H)
}

g1_integration_imag <- function(lower, upper, h_val, d, H) {
    .Call(`_carfima_g1_integration_imag`, lower, upper, h_val, d, H)
}

g2_integration_real <- function(lower, upper, h_val, d, H) {
    .Call(`_carfima_g2_integration_real`, lower, upper, h_val, d, H)
}

g2_integration_imag <- function(lower, upper, h_val, d, H) {
    .Call(`_carfima_g2_integration_imag`, lower, upper, h_val, d, H)
}

g1 <- function(h, d, H) {
    .Call(`_carfima_g1`, h, d, H)
}

g2 <- function(h, d, H) {
    .Call(`_carfima_g2`, h, d, H)
}

B_mat <- function(p, alpha) {
    .Call(`_carfima_B_mat`, p, alpha)
}

V_mat_sigma <- function(p, alpha, sigma) {
    .Call(`_carfima_V_mat_sigma`, p, alpha, sigma)
}

V_mat <- function(p, alpha) {
    .Call(`_carfima_V_mat`, p, alpha)
}

Gamma_Y <- function(time_lag_cov, p, A, H, beta, delta_p) {
    .Call(`_carfima_Gamma_Y`, time_lag_cov, p, A, H, beta, delta_p)
}

Gamma_Y_sigma <- function(time_lag_cov, p, A, H, beta, delta_p, sigma) {
    .Call(`_carfima_Gamma_Y_sigma`, time_lag_cov, p, A, H, beta, delta_p, sigma)
}

cpp_carfima_bayes <- function(loglik, Y, time, param_ini, param_scale, ar_p, ma_q, n_warm, n_sample) {
    .Call(`_carfima_cpp_carfima_bayes`, loglik, Y, time, param_ini, param_scale, ar_p, ma_q, n_warm, n_sample)
}

cpp_carfima_loglik <- function(Yold, time, p, q, parameter) {
    .Call(`_carfima_cpp_carfima_loglik`, Yold, time, p, q, parameter)
}

cpp_carfima_loglik_nosigma <- function(Yold, time, p, q, parameter) {
    .Call(`_carfima_cpp_carfima_loglik_nosigma`, Yold, time, p, q, parameter)
}

rtruncnorm <- function(mean, sd, lbd, rbd) {
    .Call(`_carfima_rtruncnorm`, mean, sd, lbd, rbd)
}

dtruncnorm <- function(x, mean, sd, lower, upper) {
    .Call(`_carfima_dtruncnorm`, x, mean, sd, lower, upper)
}

